# Generated by Django 6.1.1 on 2026-09-16 11:08

from django.db import migrations

DEFAULT_CATEGORIES = ["Electronics", "Documents", "Bags", "Keys", "Clothing", "Accessories", "Other"]


def seed_categories(apps, schema_editor):
    Category = apps.get_model("reports", "Category")
    for name in DEFAULT_CATEGORIES:
        Category.objects.get_or_create(name=name)


def unseed_categories(apps, schema_editor):
    Category = apps.get_model("reports", "Category")
    Category.objects.filter(name__in=DEFAULT_CATEGORIES).delete()

class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = []
