# Generated by Django 6.1.1 on 2026-09-17 17:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0002_seed_categories"),
    ]

    operations = [
        migrations.CreateModel(
            name="Match",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveSmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "matched_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_matched",
                        to="reports.report",
                    ),
                ),
                (
                    "primary_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="matches_as_primary",
                        to="reports.report",
                    ),
                ),
            ],
            options={
                "ordering": ["-score"],
                "unique_together": {("primary_report", "matched_report")},
            },
        ),
    ]
