# Generated by Django 6.1.1 on 2026-09-17 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_review"),
    ]

    operations = [
        migrations.AddField(
            model_name="match",
            name="confirmed",
            field=models.BooleanField(default=False),
        ),
    ]
